### ISSUE TITLE
Error: Missing the following variables: user_id, screen_name, account_created_at, text, display_text

### ISSUE THREAD

**Issue by VictorSuarezL** [mkearney/tweetbotornot2#10]
I have a total of 50,000 user_ids of which I want to know the probability of being a bot. To avoid response problems I have divided the data frame into a nested data frame of 900 user_ids each. The predict_bot function follows a normal behavior until it throws the next error: 

` Error: Missing the following variables: user_id, screen_name, account_created_at, text, display_text_width, profile_background_url, profile_banner_url, profile_expanded_url, place_full_name, reply_to_status_id, media_type, hashtags, urls_expanded_url, media_expanded_url, ext_media_expanded_url, mentions_user_id, source, profile_image_url, account_created_at, lang, is_retweet, is_quote, statuses_count, followers_count, friends_count, favourites_count, verified `

**Comment by Reyza96** [comment]
I know this issue is closed but it was never really solved and I'm having the exact same issue. Does anyone know why this might be happening?

**Comment by VictorSuarezL** [comment]
Hi @Reyza96 in my case the problem was the time rate limit. Once it is exceeded throws this error. So you should avoid to reach the rate limit. There are several functions to do so! Hope it helps :)

**Comment by Madleenbnz** [comment]
Hi @VictorSuarezL or @Reyza96 do you found eny solution to aviod to reach the rate limit? For me it also happens with five usernames... happy to get feedback!
