### ISSUE TITLE
Problem with install

### ISSUE THREAD

**Issue by sms1962** [mkearney/tweetbotornot2#2]
Hi,

When I try to install tweetornotbot2 using the command:

`install.packages("tweetbotornot2")`

I get an error:

> Warning in install.packages :
> package ‘tweetbotornot2’ is not available (for R version 3.6.0)

The same on Rstudio.Cloud and my local Rstudio

This is a sessioninfo() from new project in Rstudio.cloud

> R version 3.6.0 (2019-04-26)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 16.04.6 LTS
> 
> Matrix products: default
> BLAS:   /usr/lib/atlas-base/atlas/libblas.so.3.0
> LAPACK: /usr/lib/atlas-base/atlas/liblapack.so.3.0
> 
> locale:
>  [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8        LC_COLLATE=C.UTF-8    
>  [5] LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8    LC_PAPER=C.UTF-8       LC_NAME=C             
>  [9] LC_ADDRESS=C           LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> loaded via a namespace (and not attached):
> [1] compiler_3.6.0 tools_3.6.0

**Comment by mkearney** [comment]
It's not on CRAN yet sorry. Try 

remotes::install_github("mkearney/tweetbotornot2")

**Comment by sms1962** [comment]
Thanks
